---
apiVersion: v1
kind: Service
metadata:
  name: job-controller
spec:
  ports:
  - port: 8000
    protocol: TCP
    name: rotisserie-app
  selector:
    app: rotisserie-app
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: job-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: job-controller
    spec:
      containers:
      - name: workshop
        image: eggshell/job-controller
        ports:
          - containerPort: 8000
